POLICIES = [
    # ===== MORTGAGE =====
    {"id": "MORTGAGE-001", "title": "Mortgage Escrow Shortages",
     "content": "Escrow account shortages or overages must be reviewed within 10 business days. Provide a detailed escrow analysis statement showing the shortage calculation."},
    {"id": "MORTGAGE-002", "title": "Misapplied Mortgage Payments",
     "content": "Payments applied to the wrong account or misallocated between principal and interest must be corrected within 5 business days, with late fees reversed if the error was on the servicer's side."},
    {"id": "MORTGAGE-003", "title": "Loan Modification Requests",
     "content": "Loan modification and forbearance requests must be acknowledged within 5 business days and a written decision provided within 30 days."},
    {"id": "MORTGAGE-004", "title": "Foreclosure Complaints",
     "content": "Any complaint mentioning foreclosure, notice of default, or a scheduled sale date must be escalated immediately to the legal/compliance team. Never auto-resolved."},
    {"id": "MORTGAGE-005", "title": "Mortgage Transfer/Servicer Change Issues",
     "content": "Complaints about a mortgage being transferred to a new servicer without notice must be resolved within 7 business days, confirming continuity of payment history."},
    {"id": "MORTGAGE-006", "title": "PMI Removal Disputes",
     "content": "Private mortgage insurance removal disputes are reviewed within 10 business days against loan-to-value documentation."},

    # ===== CREDIT CARD =====
    {"id": "CREDITCARD-001", "title": "Unauthorized Transaction Disputes",
     "content": "Unauthorized or fraudulent charges must be investigated within 10 business days. Provisional credit should be issued within 2 business days pending investigation."},
    {"id": "CREDITCARD-002", "title": "Billing Error Disputes",
     "content": "Billing errors such as duplicate charges or incorrect amounts are resolved within 5-7 business days if transaction records are available."},
    {"id": "CREDITCARD-003", "title": "Interest Rate and Fee Complaints",
     "content": "Disputes over interest rate changes or fee assessments are reviewed within 7 business days, referencing the cardholder agreement."},
    {"id": "CREDITCARD-004", "title": "Credit Limit Decrease Complaints",
     "content": "Sudden credit limit decreases without notice are reviewed within 7 business days; the consumer must be informed of the specific reason."},
    {"id": "CREDITCARD-005", "title": "Rewards Program Disputes",
     "content": "Missing or miscalculated rewards points are corrected within 10 business days upon verification of qualifying transactions."},
    {"id": "CREDITCARD-006", "title": "Card Application Denial",
     "content": "Credit card application denials must include an adverse action notice with specific reasons, sent within 30 days per ECOA/FCRA."},

    # ===== DEBT COLLECTION =====
    {"id": "DEBTCOLLECTION-001", "title": "Debt Not Owed / Already Paid",
     "content": "Complaints stating the debt is not owed or was already paid must be escalated to compliance with supporting documentation requested from the consumer."},
    {"id": "DEBTCOLLECTION-002", "title": "Harassment or Improper Contact",
     "content": "Complaints alleging harassment, threats, or contact outside permitted hours (before 8am/after 9pm) must always escalate to compliance/legal due to regulatory risk."},
    {"id": "DEBTCOLLECTION-003", "title": "Debt Verification Requests",
     "content": "Consumers requesting debt verification must receive validation documentation within 30 days; collection activity should pause until verification is provided."},
    {"id": "DEBTCOLLECTION-004", "title": "Wrong Amount Collected",
     "content": "Disputes over the collected amount differing from the original balance are reviewed within 10 business days against the original creditor's records."},
    {"id": "DEBTCOLLECTION-005", "title": "Communication Tactics Complaints",
     "content": "Complaints about aggressive, misleading, or repeated communication tactics must be escalated to compliance for review of collector conduct."},
    {"id": "DEBTCOLLECTION-006", "title": "Third-Party Contact Complaints",
     "content": "Complaints about collectors contacting family, friends, or employers must be escalated immediately, as this may violate contact restrictions."},
    {"id": "DEBTCOLLECTION-007", "title": "Statute of Limitations Disputes",
     "content": "Complaints claiming the debt is time-barred under the statute of limitations must be escalated to legal for verification before further collection."},

    # ===== CREDIT REPORTING =====
    {"id": "CREDITREPORT-001", "title": "Incorrect Information Disputes",
     "content": "Incorrect information on a credit report must be investigated with the furnishing institution within 30 days per FCRA requirements."},
    {"id": "CREDITREPORT-002", "title": "Identity Theft / Mixed Files",
     "content": "Complaints involving identity theft or mixed credit files must be escalated immediately and a fraud alert recommended to the consumer."},
    {"id": "CREDITREPORT-003", "title": "Investigation Outcome Disputes",
     "content": "If a consumer disputes the outcome of a prior investigation, escalate to a senior reviewer rather than repeating the same automated process."},
    {"id": "CREDITREPORT-004", "title": "Reporting Company's Investigation Delay",
     "content": "If the credit reporting company's investigation exceeds 30 days, escalate immediately as this is a regulatory violation."},
    {"id": "CREDITREPORT-005", "title": "Improper Use of Credit Report",
     "content": "Complaints about a credit report being accessed without permissible purpose must be escalated to compliance/legal."},

    # ===== BANK ACCOUNT =====
    {"id": "BANKACCOUNT-001", "title": "Account Access Issues",
     "content": "Login, ATM, or debit card access issues are resolved within 3-5 business days after identity verification."},
    {"id": "BANKACCOUNT-002", "title": "Deposit and Withdrawal Discrepancies",
     "content": "Missing deposits or unauthorized withdrawals are investigated within 5 business days; provisional credit considered per Reg E timelines."},
    {"id": "BANKACCOUNT-003", "title": "Account Opening/Closing Issues",
     "content": "Delays or denials in account opening or closing are reviewed within 5 business days, with a clear reason provided to the consumer."},
    {"id": "BANKACCOUNT-004", "title": "Overdraft Fee Disputes",
     "content": "Disputed overdraft fees are reviewed within 5 business days against the account's opt-in overdraft agreement."},
    {"id": "BANKACCOUNT-005", "title": "Account Freeze/Hold Complaints",
     "content": "Complaints about frozen accounts or holds on funds must be reviewed within 3 business days and a specific reason communicated to the consumer."},

    # ===== STUDENT LOAN =====
    {"id": "STUDENTLOAN-001", "title": "Loan Servicing Errors",
     "content": "Payment application errors or issues following a servicing transfer are reviewed within 10 business days."},
    {"id": "STUDENTLOAN-002", "title": "Loan Forgiveness Disputes",
     "content": "Complaints involving loan forgiveness program denials must be escalated to a specialist review team, never auto-resolved."},
    {"id": "STUDENTLOAN-003", "title": "Income-Driven Repayment Issues",
     "content": "Errors in income-driven repayment plan calculations are reviewed within 10 business days against submitted income documentation."},
    {"id": "STUDENTLOAN-004", "title": "Deferment/Forbearance Disputes",
     "content": "Denied or delayed deferment/forbearance requests are reviewed within 7 business days."},

        # ===== CONSUMER LOAN (expanded) =====
    {"id": "CONSUMERLOAN-001", "title": "Auto/Personal Loan Servicing",
     "content": "General servicing complaints on auto or personal loans are reviewed within 7 business days."},
    {"id": "CONSUMERLOAN-002", "title": "Repossession Disputes",
     "content": "Any complaint mentioning vehicle repossession must be escalated immediately to the legal team, including disputes over notice period or post-repossession sale value."},
    {"id": "CONSUMERLOAN-003", "title": "Loan Payoff Amount Disputes",
     "content": "Disputes over the payoff amount owed are reviewed within 5 business days against the amortization schedule."},
    {"id": "CONSUMERLOAN-004", "title": "Add-On Product Complaints",
     "content": "Complaints about add-on products (GAP insurance, extended warranties) bundled into the loan without clear consent are escalated to compliance within 7 business days."},
    {"id": "CONSUMERLOAN-005", "title": "Co-Signer Release Disputes",
     "content": "Requests for co-signer release that were denied or delayed are reviewed within 10 business days against the loan agreement's release criteria."},
    {"id": "CONSUMERLOAN-006", "title": "Loan Origination Fee Disputes",
     "content": "Disputes over undisclosed or excessive origination fees are reviewed within 7 business days against the Truth in Lending disclosure provided at closing."},

    # ===== MONEY TRANSFERS (expanded) =====
    {"id": "MONEYTRANSFER-001", "title": "Failed or Delayed Transfers",
     "content": "Failed or delayed money transfers are investigated within 5 business days with a tracking reference provided to the consumer, consistent with Regulation E remittance transfer error-resolution timelines."},
    {"id": "MONEYTRANSFER-002", "title": "Suspected Fraudulent Transfers",
     "content": "Suspected unauthorized or fraudulent transfers must be escalated to the fraud team immediately and the account flagged, per Regulation E unauthorized transfer provisions."},
    {"id": "MONEYTRANSFER-003", "title": "Incorrect Transfer Amount/Recipient",
     "content": "Complaints about an incorrect transfer amount or wrong recipient are investigated within 5 business days; recall attempted if possible, and the sender notified of the resolution."},
    {"id": "MONEYTRANSFER-004", "title": "International Remittance Disclosure Disputes",
     "content": "Complaints that the actual exchange rate or fees charged differ from the pre-transfer disclosure must be escalated to compliance, as this may violate Regulation E's remittance transfer disclosure rules."},
    {"id": "MONEYTRANSFER-005", "title": "Remittance Cancellation Requests",
     "content": "Cancellation requests submitted within 30 minutes of a remittance transfer must be honored per Regulation E; delayed or denied cancellations are escalated immediately."},
    {"id": "MONEYTRANSFER-006", "title": "P2P Payment App Disputes",
     "content": "Disputes involving peer-to-peer payment apps (e.g., sending money to the wrong handle) are reviewed within 5 business days; these transfers are covered under EFTA/Regulation E."},

    # ===== PAYDAY LOAN (expanded) =====
    {"id": "PAYDAY-001", "title": "Fee and Rollover Disputes",
     "content": "Payday loan fee or rollover term disputes are reviewed within 5 business days against the original loan agreement."},
    {"id": "PAYDAY-002", "title": "Predatory Lending Complaints",
     "content": "Complaints alleging predatory or deceptive lending practices, including APR misrepresentation, must be escalated to compliance immediately."},
    {"id": "PAYDAY-003", "title": "Unauthorized Auto-Debit Complaints",
     "content": "Complaints about unauthorized repeated debit attempts from a linked account must be escalated to compliance and debits halted immediately."},
    {"id": "PAYDAY-004", "title": "State Licensing Compliance Disputes",
     "content": "Complaints alleging the lender is not properly licensed in the consumer's state must be escalated to legal for verification before further collection or communication."},
    {"id": "PAYDAY-005", "title": "Loan Renewal Without Consent",
     "content": "Complaints about a payday loan being automatically renewed or extended without the consumer's explicit consent must be escalated to compliance within 5 business days."},

    # ===== PREPAID CARD (expanded) =====
    {"id": "PREPAID-001", "title": "Balance and Fee Disputes",
     "content": "Prepaid card balance discrepancies or unexpected fees are resolved within 5 business days, consistent with Regulation E prepaid account disclosure requirements."},
    {"id": "PREPAID-002", "title": "Card Issuer Liability Disputes",
     "content": "If the card issuer denies liability for a disputed transaction, escalate to a senior reviewer with full transaction history; Regulation E limits consumer liability for unauthorized transfers when reported promptly."},
    {"id": "PREPAID-003", "title": "Lost or Stolen Card Reporting",
     "content": "Lost or stolen prepaid card reports must be actioned within 24 hours to freeze the card and issue a replacement."},
    {"id": "PREPAID-004", "title": "Registration/Activation Failures",
     "content": "Complaints about failed card registration or activation preventing access to funds are resolved within 3 business days."},
    {"id": "PREPAID-005", "title": "Error Resolution Timeline Complaints",
     "content": "If a prepaid account error investigation exceeds the Regulation E timeline (generally 10 business days, or 20 for new accounts), escalate immediately as a compliance issue."},

    # ===== OTHER / GENERAL (expanded) =====
    {"id": "OTHER-001", "title": "General Financial Service Issues",
     "content": "Uncommon or miscellaneous financial service complaints are reviewed case-by-case within 10 business days."},
    {"id": "OTHER-002", "title": "Unclear Regulatory Category",
     "content": "If a complaint's regulatory category is unclear or spans multiple products, escalate to compliance for classification before responding."},
    {"id": "OTHER-003", "title": "Virtual Currency Complaints",
     "content": "Complaints involving cryptocurrency exchanges or wallets are reviewed case-by-case; escalate any complaint involving suspected fraud or lost funds immediately, since virtual currency transfers may fall outside standard EFTA protections."},
    {"id": "OTHER-004", "title": "Data Privacy Complaints",
     "content": "Complaints about mishandling of personal financial data must be escalated to the privacy/compliance team within 3 business days."},
    {"id": "OTHER-005", "title": "Discrimination Complaints",
     "content": "Any complaint alleging discriminatory treatment in lending or account decisions must be escalated immediately to compliance/legal per ECOA (Equal Credit Opportunity Act)."},
    {"id": "OTHER-006", "title": "Multi-Product Complaint Handling",
     "content": "Complaints spanning more than one product line (e.g., a mortgage issue tied to a linked bank account) are routed to the primary product's team, with cross-reference notes for the secondary team."},
]




